spring:
  datasource:
    url: jdbc:h2:mem:schoolmngtdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: root
    password: rootpassword
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true			#this allow to access to the db via: http://localhost:8080/h2-console (default)
      path: /h2-console		#we can update the path too to something else
      settings.trace: false	#other settings
      settings.web-allow-others: false
  mvc.servlet.path: /api 

# jdbc:h2:mem:schoolmngtdb - this is memory db only - will clear every time | We can change to file based jdbc:h2:file:/data/demo

# spring.sql.init.mode: never - for this the schema.sql and data.sql will never be called to init schema and data at all.
# For this project, we will use hibernat and data.sql

# server.servlet.context-path: /demo  - context path
# spring.mvc.servlet.path: /api       - servlet path dispatch from all httprequest to corresponding controller